global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server1'
    static_configs:
      - targets: ['localhost:5555']
      
  - job_name: 'server2'
    static_configs:
      - targets: ['localhost:5555']
      
  - job_name: 'server3'
    static_configs:
      - targets: ['localhost:5555']
      
